version: "3.8"
services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3005:3005"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none